version: '3'
services:
  myapp:
    container_name: SLA-Monitor
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080" 
    depends_on:
      - redis
    environment:
      # TMF_URL: http://172.28.3.126:31080/tmf-api/productCatalogManagement/v4/productOffering/ # TMF Catalog URL
      TMF_URL: http://172.28.3.15:31080/tmf-api/productCatalogManagement/v4/productOffering/did/
      SCLCM_URL: http://172.28.3.6:31080/smart-contract-lifecycle-manager/api/v1/service-level-agreement # SCLCM URL 
      DL_SUB_URL: http://172.28.3.94:8080/datalake/v1/stream_data/register/ # Datalake subscription URL
      REDIS_URL: redis://redis:6379 # Redis Host 
      DL_USER_ID: sla-monitor # Datalake User Id  
      KAFKA_TOPIC_IN: sla-monitor-topic-in
      KAFKA_TOPIC_OUT: sla-monitor-topic-out
      KAFKA_TOPIC_SLA: isbp-topic
      KAFKA_GROUP_ID : "none"
      KAFKA_HOST : "172.28.3.196:9092"



  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
 