apiVersion: v1
kind: Config
clusters:
- name: "platcmp"
  cluster:
    server: "https://172.28.3.15:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl5TURReE16RXdNalkwTlZvWERUTXlNRFF4TURFd01qWTBOVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU1HY2dBS1NBdWptCkpPa1VxcjRKaGk1bjdRaEhCZ1F2alVxZGpvV3JiMXNPQ1ZIRnZXVDZKc\
      mZTYjkwdGU3ZEI3RktEVWRROS9YQ2sKdTNiMHJ4d2lGSDN6Z1dDdTdIQnRVMlh5Ukk3RlFyWk1wS\
      1pPN0JtakROUy9CK1c2R3pLeDdwT0g1dmpZNWVCawpCdS9NaVVOUTUzNnp2WnpFQVd1WkRlZFlmL\
      1lsamJVSnJSWDJMVHF4Q252V0J6VHlFbGxyaTlLZndVUWp3VWVZCnZ3bklDRG1rQ09OTjhCQXRnV\
      0F2WjZvVDJiWWwxUnhpNWFvYk8xK3pjVzhhSCtVK1kzdTVERUdPOStzL1d1TUUKYytYbkc0V1ZCK\
      zUxYTg1cTh4MGlORUZpcmRmTS9KZUJCT3ljL25Fa2lyeU9RUHVVTXkyZHI2U3hnNy9ZU0JZbApaR\
      UFOc2xQb0pUTUNBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSElOY2laeHRjVkNIWFZGMXZ4VlQ2b\
      FJpS0svSW5nU1poSDIKdGNNYnZPZS95OUh5V3VRMUYybDBUQ0NxZXVJdnlLOTVPYm82T1p4V05yZ\
      2Y4aURLYU9RV3Y0aDY4TWlHM01VYQpKcXJxZUoxNCt5NnBQVUM5QkowSUJIMklROWFSUHVzemRxK\
      0hVbUhwdllCN1ZGZXRGQjhIU3F0enFYakdvRDJLCkNWZ0ZYRndNMk9UVUp6RE1hM3IxeFlCNytkd\
      jU4RDd0bHcxNytSWXZqM2xhWFJCUWJ3MXI2cUNCV1U1aFpoZVAKZzRjS3VaSzFReVl5WEpaMmppd\
      GxEWndVYjlUTko4RTlVb2RqSXJhbHVyY0Jub3hIYUZxbmxBZ3U4MStmcnRNTgo3RzBDTmkxTnczZ\
      EhRbkQ3STNQNUpPMERvdjB5cVZ3MUtoTG8wTm9CM25uSnFydlNpNUU9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"

users:
- name: "platcmp"
  user:
    token: "kubeconfig-user-8rbnq.c-99lbp:927c6p4h2xn4sh8dj2nzcwftvxq2hjlnwnvpnplg6wjbttgf426pmr"


contexts:
- name: "platcmp"
  context:
    user: "platcmp"
    cluster: "platcmp"

current-context: "platcmp"

